// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/captcha.proto

package captcha

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Captcha service

type CaptchaService interface {
	MakeCaptcha(ctx context.Context, in *MakeCaptchaReq, opts ...client.CallOption) (*MakeCaptchaResp, error)
	VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...client.CallOption) (*VerifyCaptchaResp, error)
}

type captchaService struct {
	c    client.Client
	name string
}

func NewCaptchaService(name string, c client.Client) CaptchaService {
	return &captchaService{
		c:    c,
		name: name,
	}
}

func (c *captchaService) MakeCaptcha(ctx context.Context, in *MakeCaptchaReq, opts ...client.CallOption) (*MakeCaptchaResp, error) {
	req := c.c.NewRequest(c.name, "Captcha.MakeCaptcha", in)
	out := new(MakeCaptchaResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaService) VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...client.CallOption) (*VerifyCaptchaResp, error) {
	req := c.c.NewRequest(c.name, "Captcha.VerifyCaptcha", in)
	out := new(VerifyCaptchaResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Captcha service

type CaptchaHandler interface {
	MakeCaptcha(context.Context, *MakeCaptchaReq, *MakeCaptchaResp) error
	VerifyCaptcha(context.Context, *VerifyCaptchaReq, *VerifyCaptchaResp) error
}

func RegisterCaptchaHandler(s server.Server, hdlr CaptchaHandler, opts ...server.HandlerOption) error {
	type captcha interface {
		MakeCaptcha(ctx context.Context, in *MakeCaptchaReq, out *MakeCaptchaResp) error
		VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, out *VerifyCaptchaResp) error
	}
	type Captcha struct {
		captcha
	}
	h := &captchaHandler{hdlr}
	return s.Handle(s.NewHandler(&Captcha{h}, opts...))
}

type captchaHandler struct {
	CaptchaHandler
}

func (h *captchaHandler) MakeCaptcha(ctx context.Context, in *MakeCaptchaReq, out *MakeCaptchaResp) error {
	return h.CaptchaHandler.MakeCaptcha(ctx, in, out)
}

func (h *captchaHandler) VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, out *VerifyCaptchaResp) error {
	return h.CaptchaHandler.VerifyCaptcha(ctx, in, out)
}
