// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/captcha.proto

package captcha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// height int, width int, length int
type MakeCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeCaptchaReq) Reset() {
	*x = MakeCaptchaReq{}
	mi := &file_proto_captcha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeCaptchaReq) ProtoMessage() {}

func (x *MakeCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_captcha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeCaptchaReq.ProtoReflect.Descriptor instead.
func (*MakeCaptchaReq) Descriptor() ([]byte, []int) {
	return file_proto_captcha_proto_rawDescGZIP(), []int{0}
}

func (x *MakeCaptchaReq) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MakeCaptchaReq) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MakeCaptchaReq) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// string, string, string, error
type MakeCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	B64S          string                 `protobuf:"bytes,2,opt,name=b64s,proto3" json:"b64s,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeCaptchaResp) Reset() {
	*x = MakeCaptchaResp{}
	mi := &file_proto_captcha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeCaptchaResp) ProtoMessage() {}

func (x *MakeCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_captcha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeCaptchaResp.ProtoReflect.Descriptor instead.
func (*MakeCaptchaResp) Descriptor() ([]byte, []int) {
	return file_proto_captcha_proto_rawDescGZIP(), []int{1}
}

func (x *MakeCaptchaResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MakeCaptchaResp) GetB64S() string {
	if x != nil {
		return x.B64S
	}
	return ""
}

func (x *MakeCaptchaResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type VerifyCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaReq) Reset() {
	*x = VerifyCaptchaReq{}
	mi := &file_proto_captcha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaReq) ProtoMessage() {}

func (x *VerifyCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_captcha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaReq.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaReq) Descriptor() ([]byte, []int) {
	return file_proto_captcha_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCaptchaReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyCaptchaReq) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type VerifyCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerifyResult  bool                   `protobuf:"varint,1,opt,name=verifyResult,proto3" json:"verifyResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaResp) Reset() {
	*x = VerifyCaptchaResp{}
	mi := &file_proto_captcha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaResp) ProtoMessage() {}

func (x *VerifyCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_captcha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaResp.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaResp) Descriptor() ([]byte, []int) {
	return file_proto_captcha_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCaptchaResp) GetVerifyResult() bool {
	if x != nil {
		return x.VerifyResult
	}
	return false
}

var File_proto_captcha_proto protoreflect.FileDescriptor

const file_proto_captcha_proto_rawDesc = "" +
	"\n" +
	"\x13proto/captcha.proto\x12\acaptcha\"V\n" +
	"\x0eMakeCaptchaReq\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\"M\n" +
	"\x0fMakeCaptchaResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04b64s\x18\x02 \x01(\tR\x04b64s\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\":\n" +
	"\x10VerifyCaptchaReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"7\n" +
	"\x11VerifyCaptchaResp\x12\"\n" +
	"\fverifyResult\x18\x01 \x01(\bR\fverifyResult2\x93\x01\n" +
	"\aCaptcha\x12@\n" +
	"\vMakeCaptcha\x12\x17.captcha.MakeCaptchaReq\x1a\x18.captcha.MakeCaptchaResp\x12F\n" +
	"\rVerifyCaptcha\x12\x19.captcha.VerifyCaptchaReq\x1a\x1a.captcha.VerifyCaptchaRespB\x11Z\x0f./proto;captchab\x06proto3"

var (
	file_proto_captcha_proto_rawDescOnce sync.Once
	file_proto_captcha_proto_rawDescData []byte
)

func file_proto_captcha_proto_rawDescGZIP() []byte {
	file_proto_captcha_proto_rawDescOnce.Do(func() {
		file_proto_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_captcha_proto_rawDesc), len(file_proto_captcha_proto_rawDesc)))
	})
	return file_proto_captcha_proto_rawDescData
}

var file_proto_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_captcha_proto_goTypes = []any{
	(*MakeCaptchaReq)(nil),    // 0: captcha.MakeCaptchaReq
	(*MakeCaptchaResp)(nil),   // 1: captcha.MakeCaptchaResp
	(*VerifyCaptchaReq)(nil),  // 2: captcha.VerifyCaptchaReq
	(*VerifyCaptchaResp)(nil), // 3: captcha.VerifyCaptchaResp
}
var file_proto_captcha_proto_depIdxs = []int32{
	0, // 0: captcha.Captcha.MakeCaptcha:input_type -> captcha.MakeCaptchaReq
	2, // 1: captcha.Captcha.VerifyCaptcha:input_type -> captcha.VerifyCaptchaReq
	1, // 2: captcha.Captcha.MakeCaptcha:output_type -> captcha.MakeCaptchaResp
	3, // 3: captcha.Captcha.VerifyCaptcha:output_type -> captcha.VerifyCaptchaResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_captcha_proto_init() }
func file_proto_captcha_proto_init() {
	if File_proto_captcha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_captcha_proto_rawDesc), len(file_proto_captcha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_captcha_proto_goTypes,
		DependencyIndexes: file_proto_captcha_proto_depIdxs,
		MessageInfos:      file_proto_captcha_proto_msgTypes,
	}.Build()
	File_proto_captcha_proto = out.File
	file_proto_captcha_proto_goTypes = nil
	file_proto_captcha_proto_depIdxs = nil
}
