// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/rbacManager.proto

package rbacManager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 管理员对应的结构体
type ManagerModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	RoleId        int64                  `protobuf:"varint,7,opt,name=roleId,proto3" json:"roleId,omitempty"`
	AddTime       int64                  `protobuf:"varint,8,opt,name=addTime,proto3" json:"addTime,omitempty"`
	IsSuper       int64                  `protobuf:"varint,9,opt,name=isSuper,proto3" json:"isSuper,omitempty"`
	Role          *RoleModel             `protobuf:"bytes,10,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerModel) Reset() {
	*x = ManagerModel{}
	mi := &file_proto_rbacManager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerModel) ProtoMessage() {}

func (x *ManagerModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerModel.ProtoReflect.Descriptor instead.
func (*ManagerModel) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{0}
}

func (x *ManagerModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ManagerModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ManagerModel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ManagerModel) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ManagerModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ManagerModel) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ManagerModel) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ManagerModel) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *ManagerModel) GetIsSuper() int64 {
	if x != nil {
		return x.IsSuper
	}
	return 0
}

func (x *ManagerModel) GetRole() *RoleModel {
	if x != nil {
		return x.Role
	}
	return nil
}

// 角色对应的结构体
type RoleModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	AddTime       int64                  `protobuf:"varint,5,opt,name=addTime,proto3" json:"addTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleModel) Reset() {
	*x = RoleModel{}
	mi := &file_proto_rbacManager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleModel) ProtoMessage() {}

func (x *RoleModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleModel.ProtoReflect.Descriptor instead.
func (*RoleModel) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{1}
}

func (x *RoleModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoleModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleModel) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleModel) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

type ManagerGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerGetRequest) Reset() {
	*x = ManagerGetRequest{}
	mi := &file_proto_rbacManager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerGetRequest) ProtoMessage() {}

func (x *ManagerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerGetRequest.ProtoReflect.Descriptor instead.
func (*ManagerGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{2}
}

func (x *ManagerGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ManagerGetRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ManagerGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerList   []*ManagerModel        `protobuf:"bytes,1,rep,name=ManagerList,proto3" json:"ManagerList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerGetResponse) Reset() {
	*x = ManagerGetResponse{}
	mi := &file_proto_rbacManager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerGetResponse) ProtoMessage() {}

func (x *ManagerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerGetResponse.ProtoReflect.Descriptor instead.
func (*ManagerGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{3}
}

func (x *ManagerGetResponse) GetManagerList() []*ManagerModel {
	if x != nil {
		return x.ManagerList
	}
	return nil
}

type ManagerAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	RoleId        int64                  `protobuf:"varint,6,opt,name=roleId,proto3" json:"roleId,omitempty"`
	AddTime       int64                  `protobuf:"varint,7,opt,name=addTime,proto3" json:"addTime,omitempty"`
	IsSuper       int64                  `protobuf:"varint,8,opt,name=isSuper,proto3" json:"isSuper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerAddRequest) Reset() {
	*x = ManagerAddRequest{}
	mi := &file_proto_rbacManager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerAddRequest) ProtoMessage() {}

func (x *ManagerAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerAddRequest.ProtoReflect.Descriptor instead.
func (*ManagerAddRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{4}
}

func (x *ManagerAddRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ManagerAddRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ManagerAddRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ManagerAddRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ManagerAddRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ManagerAddRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ManagerAddRequest) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *ManagerAddRequest) GetIsSuper() int64 {
	if x != nil {
		return x.IsSuper
	}
	return 0
}

type ManagerAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerAddResponse) Reset() {
	*x = ManagerAddResponse{}
	mi := &file_proto_rbacManager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerAddResponse) ProtoMessage() {}

func (x *ManagerAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerAddResponse.ProtoReflect.Descriptor instead.
func (*ManagerAddResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{5}
}

func (x *ManagerAddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ManagerAddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ManagerEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	RoleId        int64                  `protobuf:"varint,7,opt,name=roleId,proto3" json:"roleId,omitempty"`
	AddTime       int64                  `protobuf:"varint,8,opt,name=addTime,proto3" json:"addTime,omitempty"`
	IsSuper       int64                  `protobuf:"varint,9,opt,name=isSuper,proto3" json:"isSuper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerEditRequest) Reset() {
	*x = ManagerEditRequest{}
	mi := &file_proto_rbacManager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerEditRequest) ProtoMessage() {}

func (x *ManagerEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerEditRequest.ProtoReflect.Descriptor instead.
func (*ManagerEditRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{6}
}

func (x *ManagerEditRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ManagerEditRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ManagerEditRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ManagerEditRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ManagerEditRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ManagerEditRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ManagerEditRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ManagerEditRequest) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *ManagerEditRequest) GetIsSuper() int64 {
	if x != nil {
		return x.IsSuper
	}
	return 0
}

type ManagerEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerEditResponse) Reset() {
	*x = ManagerEditResponse{}
	mi := &file_proto_rbacManager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerEditResponse) ProtoMessage() {}

func (x *ManagerEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerEditResponse.ProtoReflect.Descriptor instead.
func (*ManagerEditResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{7}
}

func (x *ManagerEditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ManagerEditResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ManagerDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerDeleteRequest) Reset() {
	*x = ManagerDeleteRequest{}
	mi := &file_proto_rbacManager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerDeleteRequest) ProtoMessage() {}

func (x *ManagerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerDeleteRequest.ProtoReflect.Descriptor instead.
func (*ManagerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{8}
}

func (x *ManagerDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ManagerDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerDeleteResponse) Reset() {
	*x = ManagerDeleteResponse{}
	mi := &file_proto_rbacManager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerDeleteResponse) ProtoMessage() {}

func (x *ManagerDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacManager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerDeleteResponse.ProtoReflect.Descriptor instead.
func (*ManagerDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacManager_proto_rawDescGZIP(), []int{9}
}

func (x *ManagerDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ManagerDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_rbacManager_proto protoreflect.FileDescriptor

const file_proto_rbacManager_proto_rawDesc = "" +
	"\n" +
	"\x17proto/rbacManager.proto\x12\amanager\"\x90\x02\n" +
	"\fManagerModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x16\n" +
	"\x06roleId\x18\a \x01(\x03R\x06roleId\x12\x18\n" +
	"\aaddTime\x18\b \x01(\x03R\aaddTime\x12\x18\n" +
	"\aisSuper\x18\t \x01(\x03R\aisSuper\x12&\n" +
	"\x04role\x18\n" +
	" \x01(\v2\x12.manager.RoleModelR\x04role\"\x85\x01\n" +
	"\tRoleModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x18\n" +
	"\aaddTime\x18\x05 \x01(\x03R\aaddTime\"?\n" +
	"\x11ManagerGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"M\n" +
	"\x12ManagerGetResponse\x127\n" +
	"\vManagerList\x18\x01 \x03(\v2\x15.manager.ManagerModelR\vManagerList\"\xdd\x01\n" +
	"\x11ManagerAddRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x16\n" +
	"\x06roleId\x18\x06 \x01(\x03R\x06roleId\x12\x18\n" +
	"\aaddTime\x18\a \x01(\x03R\aaddTime\x12\x18\n" +
	"\aisSuper\x18\b \x01(\x03R\aisSuper\"H\n" +
	"\x12ManagerAddResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xee\x01\n" +
	"\x12ManagerEditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x16\n" +
	"\x06roleId\x18\a \x01(\x03R\x06roleId\x12\x18\n" +
	"\aaddTime\x18\b \x01(\x03R\aaddTime\x12\x18\n" +
	"\aisSuper\x18\t \x01(\x03R\aisSuper\"I\n" +
	"\x13ManagerEditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x14ManagerDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x15ManagerDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbd\x02\n" +
	"\vRbacManager\x12G\n" +
	"\n" +
	"ManagerGet\x12\x1a.manager.ManagerGetRequest\x1a\x1b.manager.ManagerGetResponse\"\x00\x12G\n" +
	"\n" +
	"ManagerAdd\x12\x1a.manager.ManagerAddRequest\x1a\x1b.manager.ManagerAddResponse\"\x00\x12J\n" +
	"\vManagerEdit\x12\x1b.manager.ManagerEditRequest\x1a\x1c.manager.ManagerEditResponse\"\x00\x12P\n" +
	"\rManagerDelete\x12\x1d.manager.ManagerDeleteRequest\x1a\x1e.manager.ManagerDeleteResponse\"\x00B\x15Z\x13./proto/rbacManagerb\x06proto3"

var (
	file_proto_rbacManager_proto_rawDescOnce sync.Once
	file_proto_rbacManager_proto_rawDescData []byte
)

func file_proto_rbacManager_proto_rawDescGZIP() []byte {
	file_proto_rbacManager_proto_rawDescOnce.Do(func() {
		file_proto_rbacManager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rbacManager_proto_rawDesc), len(file_proto_rbacManager_proto_rawDesc)))
	})
	return file_proto_rbacManager_proto_rawDescData
}

var file_proto_rbacManager_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_rbacManager_proto_goTypes = []any{
	(*ManagerModel)(nil),          // 0: manager.ManagerModel
	(*RoleModel)(nil),             // 1: manager.RoleModel
	(*ManagerGetRequest)(nil),     // 2: manager.ManagerGetRequest
	(*ManagerGetResponse)(nil),    // 3: manager.ManagerGetResponse
	(*ManagerAddRequest)(nil),     // 4: manager.ManagerAddRequest
	(*ManagerAddResponse)(nil),    // 5: manager.ManagerAddResponse
	(*ManagerEditRequest)(nil),    // 6: manager.ManagerEditRequest
	(*ManagerEditResponse)(nil),   // 7: manager.ManagerEditResponse
	(*ManagerDeleteRequest)(nil),  // 8: manager.ManagerDeleteRequest
	(*ManagerDeleteResponse)(nil), // 9: manager.ManagerDeleteResponse
}
var file_proto_rbacManager_proto_depIdxs = []int32{
	1, // 0: manager.ManagerModel.role:type_name -> manager.RoleModel
	0, // 1: manager.ManagerGetResponse.ManagerList:type_name -> manager.ManagerModel
	2, // 2: manager.RbacManager.ManagerGet:input_type -> manager.ManagerGetRequest
	4, // 3: manager.RbacManager.ManagerAdd:input_type -> manager.ManagerAddRequest
	6, // 4: manager.RbacManager.ManagerEdit:input_type -> manager.ManagerEditRequest
	8, // 5: manager.RbacManager.ManagerDelete:input_type -> manager.ManagerDeleteRequest
	3, // 6: manager.RbacManager.ManagerGet:output_type -> manager.ManagerGetResponse
	5, // 7: manager.RbacManager.ManagerAdd:output_type -> manager.ManagerAddResponse
	7, // 8: manager.RbacManager.ManagerEdit:output_type -> manager.ManagerEditResponse
	9, // 9: manager.RbacManager.ManagerDelete:output_type -> manager.ManagerDeleteResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rbacManager_proto_init() }
func file_proto_rbacManager_proto_init() {
	if File_proto_rbacManager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rbacManager_proto_rawDesc), len(file_proto_rbacManager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rbacManager_proto_goTypes,
		DependencyIndexes: file_proto_rbacManager_proto_depIdxs,
		MessageInfos:      file_proto_rbacManager_proto_msgTypes,
	}.Build()
	File_proto_rbacManager_proto = out.File
	file_proto_rbacManager_proto_goTypes = nil
	file_proto_rbacManager_proto_depIdxs = nil
}
