// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/rbacLogin.proto

package rbacLogin

import (
	fmt "fmt"
	math "math"

	proto "google.golang.org/protobuf/proto"
)

import (
	context "context"

	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RbacLogin service

type RbacLoginService interface {
	Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginResp, error)
}

type rbacLoginService struct {
	c    client.Client
	name string
}

func NewRbacLoginService(name string, c client.Client) RbacLoginService {
	return &rbacLoginService{
		c:    c,
		name: name,
	}
}

func (c *rbacLoginService) Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginResp, error) {
	req := c.c.NewRequest(c.name, "RbacLogin.Login", in)
	out := new(LoginResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RbacLogin service

type RbacLoginHandler interface {
	Login(context.Context, *LoginReq, *LoginResp) error
}

func RegisterRbacLoginHandler(s server.Server, hdlr RbacLoginHandler, opts ...server.HandlerOption) error {
	type rbacLogin interface {
		Login(ctx context.Context, in *LoginReq, out *LoginResp) error
	}
	type RbacLogin struct {
		rbacLogin
	}
	h := &rbacLoginHandler{hdlr}
	return s.Handle(s.NewHandler(&RbacLogin{h}, opts...))
}

type rbacLoginHandler struct {
	RbacLoginHandler
}

func (h *rbacLoginHandler) Login(ctx context.Context, in *LoginReq, out *LoginResp) error {
	return h.RbacLoginHandler.Login(ctx, in, out)
}
