// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/rbacLogin.proto

package rbacLogin

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManagerModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	RoleId        int64                  `protobuf:"varint,7,opt,name=roleId,proto3" json:"roleId,omitempty"`
	AddTime       int64                  `protobuf:"varint,8,opt,name=addTime,proto3" json:"addTime,omitempty"`
	IsSuper       int64                  `protobuf:"varint,9,opt,name=isSuper,proto3" json:"isSuper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerModel) Reset() {
	*x = ManagerModel{}
	mi := &file_proto_rbacLogin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerModel) ProtoMessage() {}

func (x *ManagerModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacLogin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerModel.ProtoReflect.Descriptor instead.
func (*ManagerModel) Descriptor() ([]byte, []int) {
	return file_proto_rbacLogin_proto_rawDescGZIP(), []int{0}
}

func (x *ManagerModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ManagerModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ManagerModel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ManagerModel) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ManagerModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ManagerModel) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ManagerModel) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ManagerModel) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *ManagerModel) GetIsSuper() int64 {
	if x != nil {
		return x.IsSuper
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_proto_rbacLogin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacLogin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_rbacLogin_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLogin       bool                   `protobuf:"varint,1,opt,name=isLogin,proto3" json:"isLogin,omitempty"`
	Userlist      []*ManagerModel        `protobuf:"bytes,2,rep,name=userlist,proto3" json:"userlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_proto_rbacLogin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacLogin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_proto_rbacLogin_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResp) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

func (x *LoginResp) GetUserlist() []*ManagerModel {
	if x != nil {
		return x.Userlist
	}
	return nil
}

var File_proto_rbacLogin_proto protoreflect.FileDescriptor

const file_proto_rbacLogin_proto_rawDesc = "" +
	"\n" +
	"\x15proto/rbacLogin.proto\x12\x04rbac\"\xe8\x01\n" +
	"\fManagerModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x16\n" +
	"\x06roleId\x18\a \x01(\x03R\x06roleId\x12\x18\n" +
	"\aaddTime\x18\b \x01(\x03R\aaddTime\x12\x18\n" +
	"\aisSuper\x18\t \x01(\x03R\aisSuper\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"U\n" +
	"\tLoginResp\x12\x18\n" +
	"\aisLogin\x18\x01 \x01(\bR\aisLogin\x12.\n" +
	"\buserlist\x18\x02 \x03(\v2\x12.rbac.ManagerModelR\buserlist27\n" +
	"\tRbacLogin\x12*\n" +
	"\x05Login\x12\x0e.rbac.LoginReq\x1a\x0f.rbac.LoginResp\"\x00B\x0eZ\f./proto;rbacb\x06proto3"

var (
	file_proto_rbacLogin_proto_rawDescOnce sync.Once
	file_proto_rbacLogin_proto_rawDescData []byte
)

func file_proto_rbacLogin_proto_rawDescGZIP() []byte {
	file_proto_rbacLogin_proto_rawDescOnce.Do(func() {
		file_proto_rbacLogin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rbacLogin_proto_rawDesc), len(file_proto_rbacLogin_proto_rawDesc)))
	})
	return file_proto_rbacLogin_proto_rawDescData
}

var file_proto_rbacLogin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_rbacLogin_proto_goTypes = []any{
	(*ManagerModel)(nil), // 0: rbac.ManagerModel
	(*LoginReq)(nil),     // 1: rbac.LoginReq
	(*LoginResp)(nil),    // 2: rbac.LoginResp
}
var file_proto_rbacLogin_proto_depIdxs = []int32{
	0, // 0: rbac.LoginResp.userlist:type_name -> rbac.ManagerModel
	1, // 1: rbac.RbacLogin.Login:input_type -> rbac.LoginReq
	2, // 2: rbac.RbacLogin.Login:output_type -> rbac.LoginResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rbacLogin_proto_init() }
func file_proto_rbacLogin_proto_init() {
	if File_proto_rbacLogin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rbacLogin_proto_rawDesc), len(file_proto_rbacLogin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rbacLogin_proto_goTypes,
		DependencyIndexes: file_proto_rbacLogin_proto_depIdxs,
		MessageInfos:      file_proto_rbacLogin_proto_msgTypes,
	}.Build()
	File_proto_rbacLogin_proto = out.File
	file_proto_rbacLogin_proto_goTypes = nil
	file_proto_rbacLogin_proto_depIdxs = nil
}
