// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/rbacRole.proto

package rbacRole

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	AddTime       int64                  `protobuf:"varint,5,opt,name=addTime,proto3" json:"addTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleModel) Reset() {
	*x = RoleModel{}
	mi := &file_proto_rbacRole_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleModel) ProtoMessage() {}

func (x *RoleModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleModel.ProtoReflect.Descriptor instead.
func (*RoleModel) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{0}
}

func (x *RoleModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoleModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleModel) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleModel) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

type RoleGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGetRequest) Reset() {
	*x = RoleGetRequest{}
	mi := &file_proto_rbacRole_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetRequest) ProtoMessage() {}

func (x *RoleGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetRequest.ProtoReflect.Descriptor instead.
func (*RoleGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{1}
}

func (x *RoleGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoleGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleList      []*RoleModel           `protobuf:"bytes,1,rep,name=roleList,proto3" json:"roleList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGetResponse) Reset() {
	*x = RoleGetResponse{}
	mi := &file_proto_rbacRole_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetResponse) ProtoMessage() {}

func (x *RoleGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetResponse.ProtoReflect.Descriptor instead.
func (*RoleGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{2}
}

func (x *RoleGetResponse) GetRoleList() []*RoleModel {
	if x != nil {
		return x.RoleList
	}
	return nil
}

type RoleAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	AddTime       int64                  `protobuf:"varint,4,opt,name=addTime,proto3" json:"addTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAddRequest) Reset() {
	*x = RoleAddRequest{}
	mi := &file_proto_rbacRole_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAddRequest) ProtoMessage() {}

func (x *RoleAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAddRequest.ProtoReflect.Descriptor instead.
func (*RoleAddRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{3}
}

func (x *RoleAddRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoleAddRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleAddRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleAddRequest) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

type RoleAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAddResponse) Reset() {
	*x = RoleAddResponse{}
	mi := &file_proto_rbacRole_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAddResponse) ProtoMessage() {}

func (x *RoleAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAddResponse.ProtoReflect.Descriptor instead.
func (*RoleAddResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{4}
}

func (x *RoleAddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoleAddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoleEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	AddTime       int64                  `protobuf:"varint,5,opt,name=addTime,proto3" json:"addTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleEditRequest) Reset() {
	*x = RoleEditRequest{}
	mi := &file_proto_rbacRole_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEditRequest) ProtoMessage() {}

func (x *RoleEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEditRequest.ProtoReflect.Descriptor instead.
func (*RoleEditRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{5}
}

func (x *RoleEditRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleEditRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoleEditRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleEditRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleEditRequest) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

type RoleEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleEditResponse) Reset() {
	*x = RoleEditResponse{}
	mi := &file_proto_rbacRole_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEditResponse) ProtoMessage() {}

func (x *RoleEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEditResponse.ProtoReflect.Descriptor instead.
func (*RoleEditResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{6}
}

func (x *RoleEditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoleEditResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoleDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleDeleteRequest) Reset() {
	*x = RoleDeleteRequest{}
	mi := &file_proto_rbacRole_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteRequest) ProtoMessage() {}

func (x *RoleDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteRequest.ProtoReflect.Descriptor instead.
func (*RoleDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{7}
}

func (x *RoleDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoleDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleDeleteResponse) Reset() {
	*x = RoleDeleteResponse{}
	mi := &file_proto_rbacRole_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteResponse) ProtoMessage() {}

func (x *RoleDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbacRole_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteResponse.ProtoReflect.Descriptor instead.
func (*RoleDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbacRole_proto_rawDescGZIP(), []int{8}
}

func (x *RoleDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RoleDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_rbacRole_proto protoreflect.FileDescriptor

const file_proto_rbacRole_proto_rawDesc = "" +
	"\n" +
	"\x14proto/rbacRole.proto\x12\x04rbac\"\x85\x01\n" +
	"\tRoleModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x18\n" +
	"\aaddTime\x18\x05 \x01(\x03R\aaddTime\" \n" +
	"\x0eRoleGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x0fRoleGetResponse\x12+\n" +
	"\broleList\x18\x01 \x03(\v2\x0f.rbac.RoleModelR\broleList\"z\n" +
	"\x0eRoleAddRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x12\x18\n" +
	"\aaddTime\x18\x04 \x01(\x03R\aaddTime\"E\n" +
	"\x0fRoleAddResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x0fRoleEditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x18\n" +
	"\aaddTime\x18\x05 \x01(\x03R\aaddTime\"F\n" +
	"\x10RoleEditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\x11RoleDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\x12RoleDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfe\x01\n" +
	"\bRbacRole\x128\n" +
	"\aRoleGet\x12\x14.rbac.RoleGetRequest\x1a\x15.rbac.RoleGetResponse\"\x00\x128\n" +
	"\aRoleAdd\x12\x14.rbac.RoleAddRequest\x1a\x15.rbac.RoleAddResponse\"\x00\x12;\n" +
	"\bRoleEdit\x12\x15.rbac.RoleEditRequest\x1a\x16.rbac.RoleEditResponse\"\x00\x12A\n" +
	"\n" +
	"RoleDelete\x12\x17.rbac.RoleDeleteRequest\x1a\x18.rbac.RoleDeleteResponse\"\x00B\x12Z\x10./proto/rbacRoleb\x06proto3"

var (
	file_proto_rbacRole_proto_rawDescOnce sync.Once
	file_proto_rbacRole_proto_rawDescData []byte
)

func file_proto_rbacRole_proto_rawDescGZIP() []byte {
	file_proto_rbacRole_proto_rawDescOnce.Do(func() {
		file_proto_rbacRole_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rbacRole_proto_rawDesc), len(file_proto_rbacRole_proto_rawDesc)))
	})
	return file_proto_rbacRole_proto_rawDescData
}

var file_proto_rbacRole_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_rbacRole_proto_goTypes = []any{
	(*RoleModel)(nil),          // 0: rbac.RoleModel
	(*RoleGetRequest)(nil),     // 1: rbac.RoleGetRequest
	(*RoleGetResponse)(nil),    // 2: rbac.RoleGetResponse
	(*RoleAddRequest)(nil),     // 3: rbac.RoleAddRequest
	(*RoleAddResponse)(nil),    // 4: rbac.RoleAddResponse
	(*RoleEditRequest)(nil),    // 5: rbac.RoleEditRequest
	(*RoleEditResponse)(nil),   // 6: rbac.RoleEditResponse
	(*RoleDeleteRequest)(nil),  // 7: rbac.RoleDeleteRequest
	(*RoleDeleteResponse)(nil), // 8: rbac.RoleDeleteResponse
}
var file_proto_rbacRole_proto_depIdxs = []int32{
	0, // 0: rbac.RoleGetResponse.roleList:type_name -> rbac.RoleModel
	1, // 1: rbac.RbacRole.RoleGet:input_type -> rbac.RoleGetRequest
	3, // 2: rbac.RbacRole.RoleAdd:input_type -> rbac.RoleAddRequest
	5, // 3: rbac.RbacRole.RoleEdit:input_type -> rbac.RoleEditRequest
	7, // 4: rbac.RbacRole.RoleDelete:input_type -> rbac.RoleDeleteRequest
	2, // 5: rbac.RbacRole.RoleGet:output_type -> rbac.RoleGetResponse
	4, // 6: rbac.RbacRole.RoleAdd:output_type -> rbac.RoleAddResponse
	6, // 7: rbac.RbacRole.RoleEdit:output_type -> rbac.RoleEditResponse
	8, // 8: rbac.RbacRole.RoleDelete:output_type -> rbac.RoleDeleteResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rbacRole_proto_init() }
func file_proto_rbacRole_proto_init() {
	if File_proto_rbacRole_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rbacRole_proto_rawDesc), len(file_proto_rbacRole_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rbacRole_proto_goTypes,
		DependencyIndexes: file_proto_rbacRole_proto_depIdxs,
		MessageInfos:      file_proto_rbacRole_proto_msgTypes,
	}.Build()
	File_proto_rbacRole_proto = out.File
	file_proto_rbacRole_proto_goTypes = nil
	file_proto_rbacRole_proto_depIdxs = nil
}
