// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/rbacRole.proto

package rbacRole

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RbacRole service

type RbacRoleService interface {
	RoleGet(ctx context.Context, in *RoleGetRequest, opts ...client.CallOption) (*RoleGetResponse, error)
	RoleAdd(ctx context.Context, in *RoleAddRequest, opts ...client.CallOption) (*RoleAddResponse, error)
	RoleEdit(ctx context.Context, in *RoleEditRequest, opts ...client.CallOption) (*RoleEditResponse, error)
	RoleDelete(ctx context.Context, in *RoleDeleteRequest, opts ...client.CallOption) (*RoleDeleteResponse, error)
}

type rbacRoleService struct {
	c    client.Client
	name string
}

func NewRbacRoleService(name string, c client.Client) RbacRoleService {
	return &rbacRoleService{
		c:    c,
		name: name,
	}
}

func (c *rbacRoleService) RoleGet(ctx context.Context, in *RoleGetRequest, opts ...client.CallOption) (*RoleGetResponse, error) {
	req := c.c.NewRequest(c.name, "RbacRole.RoleGet", in)
	out := new(RoleGetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacRoleService) RoleAdd(ctx context.Context, in *RoleAddRequest, opts ...client.CallOption) (*RoleAddResponse, error) {
	req := c.c.NewRequest(c.name, "RbacRole.RoleAdd", in)
	out := new(RoleAddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacRoleService) RoleEdit(ctx context.Context, in *RoleEditRequest, opts ...client.CallOption) (*RoleEditResponse, error) {
	req := c.c.NewRequest(c.name, "RbacRole.RoleEdit", in)
	out := new(RoleEditResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacRoleService) RoleDelete(ctx context.Context, in *RoleDeleteRequest, opts ...client.CallOption) (*RoleDeleteResponse, error) {
	req := c.c.NewRequest(c.name, "RbacRole.RoleDelete", in)
	out := new(RoleDeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RbacRole service

type RbacRoleHandler interface {
	RoleGet(context.Context, *RoleGetRequest, *RoleGetResponse) error
	RoleAdd(context.Context, *RoleAddRequest, *RoleAddResponse) error
	RoleEdit(context.Context, *RoleEditRequest, *RoleEditResponse) error
	RoleDelete(context.Context, *RoleDeleteRequest, *RoleDeleteResponse) error
}

func RegisterRbacRoleHandler(s server.Server, hdlr RbacRoleHandler, opts ...server.HandlerOption) error {
	type rbacRole interface {
		RoleGet(ctx context.Context, in *RoleGetRequest, out *RoleGetResponse) error
		RoleAdd(ctx context.Context, in *RoleAddRequest, out *RoleAddResponse) error
		RoleEdit(ctx context.Context, in *RoleEditRequest, out *RoleEditResponse) error
		RoleDelete(ctx context.Context, in *RoleDeleteRequest, out *RoleDeleteResponse) error
	}
	type RbacRole struct {
		rbacRole
	}
	h := &rbacRoleHandler{hdlr}
	return s.Handle(s.NewHandler(&RbacRole{h}, opts...))
}

type rbacRoleHandler struct {
	RbacRoleHandler
}

func (h *rbacRoleHandler) RoleGet(ctx context.Context, in *RoleGetRequest, out *RoleGetResponse) error {
	return h.RbacRoleHandler.RoleGet(ctx, in, out)
}

func (h *rbacRoleHandler) RoleAdd(ctx context.Context, in *RoleAddRequest, out *RoleAddResponse) error {
	return h.RbacRoleHandler.RoleAdd(ctx, in, out)
}

func (h *rbacRoleHandler) RoleEdit(ctx context.Context, in *RoleEditRequest, out *RoleEditResponse) error {
	return h.RbacRoleHandler.RoleEdit(ctx, in, out)
}

func (h *rbacRoleHandler) RoleDelete(ctx context.Context, in *RoleDeleteRequest, out *RoleDeleteResponse) error {
	return h.RbacRoleHandler.RoleDelete(ctx, in, out)
}
